name: 'search'

type: 'python:3.8'

# dependencies:
#     python3:
#        poetry: '1.1.4'

hooks:
    build: !include
        type: string
        path: build.sh
    post_deploy: !include
        type: string
        path: update_search.sh

web:
    commands:
      # Run the Meilisearch server
      start: "./meilisearch --http-addr localhost:${PORT}"

# The size of the persistent disk of the application (in MB).
disk: 2048

mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "output":
        source: local
        source_path: "output"
    "config":
        source: service
        service: files
        source_path: config
