name: 'search'

type: 'python:3.8'

# dependencies:
#     python3:
#        poetry: '1.1.4'
variables:
    env:
        POETRY_VIRTUALENVS_IN_PROJECT: true

hooks:
    build: |
        # Install Meilisearch
        curl -L https://install.meilisearch.com | sh

        # Install poetry
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        . $PLATFORM_APP_DIR/.poetry/env

        # Install dependencies for scrapy
        .poetry/bin/poetry install

        # Make scraping script executable
        chmod +x ./scrape.sh
    # build: !include
    #     type: string
    #     path: build.sh
    post_deploy: !include
        type: string
        path: update_search.sh

web:
    commands:
      # Run the Meilisearch server
      start: "./meilisearch --http-addr localhost:${PORT}"

# The size of the persistent disk of the application (in MB).
disk: 2048

mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "output":
        source: local
        source_path: "output"
    "config":
        source: service
        service: files
        source_path: config
    # "/.config":
    #     source: service
    #     service: files
    #     source_path: poetry-config
