name: 'search'

type: 'python:3.8'

variables:
    env:
        POETRY_VERSION: '1.1.4'
        POETRY_VIRTUALENVS_IN_PROJECT: true
        POETRY_VIRTUALENVS_CREATE: false

hooks:
    build: |
        # Install Meilisearch
        curl -L https://install.meilisearch.com | sh

        # Install poetry
        curl https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py >> get-poetry.py
        python get-poetry.py --version $POETRY_VERSION

        . $PLATFORM_APP_DIR/.poetry/env
        echo ". $PLATFORM_APP_DIR/.poetry/env" >> ~/.bash_profile

        # poetry config virtualenvs.create false
        # poetry config virtualenvs.in-project true
        poetry install -vvv

        # Make scraping script executable
        chmod +x ./scrape.sh

    # build: !include
    #     type: string
    #     path: build.sh

    post_deploy: !include
        type: string
        path: update_search.sh

web:
    commands:
      # Run the Meilisearch server
      start: "./meilisearch --http-addr localhost:${PORT}"

# The size of the persistent disk of the application (in MB).
disk: 2048

mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "output":
        source: local
        source_path: "output"
    "config":
        source: service
        service: files
        source_path: config
    # "/.config":
    #     source: service
    #     service: files
    #     source_path: poetry-config
