# Basics
baseURL: /
title: Deploy Friday Docs
author: Deploy Friday
description: Deploy Friday User Documentation

# Themes
theme: psh-docs
themesdir: '../../themes'

uglyurls: true
pygmentsUseClasses: true

# Language settings
languages:
  en:
    languageName: English
    weight: 10

disableKinds: ["taxonomy", "taxonomyTerm"]

baseURL: "https://docs.deploy-friday.net"

summaryLength: 3

outputs:
    home: 
      - HTML
      - JSON
      - RSS
    section:
      - HTML
      - RSS

markup:
    goldmark:
        renderer:
            unsafe: true

module:
    mounts:
        - source: "node_modules/mermaid/dist"
          target: "static/mermaid"
        - source: "node_modules/asciinema-player/dist/bundle"
          target: "static/asciinema"
        - source: "node_modules/alpinejs/dist"
          target: "static/alpinejs"

        - source: "../../shared/data"
          target: "data"

        - source: "../platform/src"
          target: "content"
          lang: "en"
        
          
        # - source: "../platform/src/add-services"
        #   target: "content/add-services"
        #   lang: "en"
        # - source: "../platform/src/administration"
        #   target: "content/administration"
        #   lang: "en"
        # - source: "../platform/src/bestpractices"
        #   target: "content/bestpractices"
        #   lang: "en"
        # - source: "../platform/src/create-apps"
        #   target: "content/create-apps"
        #   lang: "en"
        # - source: "../platform/src/dedicated-gen-2"
        #   target: "content/dedicated-gen-2"
        #   lang: "en"
        # - source: "../platform/src/dedicated-gen-3"
        #   target: "content/dedicated-gen-3"
        #   lang: "en"
        # - source: "../platform/src/define-routes"
        #   target: "content/define-routes"
        #   lang: "en"
        # - source: "../platform/src/development"
        #   target: "content/development"
        #   lang: "en"
        # - source: "../platform/src/domains"
        #   target: "content/domains"
        #   lang: "en"
        # - source: "../platform/src/environments"
        #   target: "content/environments"
        #   lang: "en"
        # - source: "../platform/src/feedback"
        #   target: "content/feedback"
        #   lang: "en"
        # - source: "../platform/src/get-started"
        #   target: "content/get-started"
        #   lang: "en"
        # - source: "../platform/src/guides"
        #   target: "content/guides"
        #   lang: "en"
        # - source: "../platform/src/increase-observability"
        #   target: "content/increase-observability"
        #   lang: "en"
        # - source: "../platform/src/integrations"
        #   target: "content/integrations"
        #   lang: "en"
        # - source: "../platform/src/languages"
        #   target: "content/languages"
        #   lang: "en"
        # - source: "../platform/src/other"
        #   target: "content/other"
        #   lang: "en"
        # - source: "../platform/src/projects"
        #   target: "content/projects"
        #   lang: "en"
        # - source: "../platform/src/security"
        #   target: "content/security"
        #   lang: "en"
        # - source: "../platform/src/tutorials"
        #   target: "content/tutorials"
        #   lang: "en"

        - source: "../platform/static/images"
          target: "static/images"


security:
  funcs:
    getenv:
    - ^GITHUB_
    - ^HUGO_HEAP_ID
  http:
    methods: none
