# Basics
baseURL: /
title: Deploy Friday Docs
author: Deploy Friday
description: Deploy Friday User Documentation

# Themes
theme: psh-docs
themesdir: '../../themes'

uglyurls: true
pygmentsUseClasses: true

# Language settings
languages:
  en:
    languageName: English
    weight: 10

disableKinds: ["taxonomy", "taxonomyTerm"]

baseURL: "https://docs.deploy-friday.net"

summaryLength: 3

outputs:
    home: 
      - HTML
      - JSON
      - RSS
    section:
      - HTML
      - RSS

markup:
    goldmark:
        renderer:
            unsafe: true

module:
    mounts:
        - source: "node_modules/mermaid/dist"
          target: "static/mermaid"
        - source: "node_modules/asciinema-player/dist/bundle"
          target: "static/asciinema"
        - source: "node_modules/alpinejs/dist"
          target: "static/alpinejs"

        - source: "../../shared/data"
          target: "data"
          
        - source: "../platform/src"
          target: "content"
          lang: "en"

        - source: "../platform/static/images"
          target: "static/images"


security:
  funcs:
    getenv:
    - ^GITHUB_
    - ^HUGO_HEAP_ID
  http:
    methods: none
