name: Linting
on:
  push:
    branches-ignore:
      - main

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.2
      with:
        # Optional
        files: __onlyModified
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}