name: Activate environment
on:
  pull_request_target:
    branches: [main]
    types:
      - opened
      - reopened
      - closed

env:
  PLATFORMSH_CLI_NO_INTERACTION: 1
  PLATFORM_PROJECT: 652soceglkw4u

jobs:
  activate_environment:
    runs-on: ubuntu-latest
    # Activate when a PR is opened, but not for forks (handled through `build-from-fork` workflow)
    if: >-
      (github.event.action == 'opened' ||
      github.event.action== 'reopened') &&
      github.event.pull_request.head.repo.id == 21975579
    steps:
      # Set up workflow environment to use the Platform.sh CLI
      - name: Set up Platform.sh CLI
        uses: ./.github/actions/set-up-cli

      - env:
          PLATFORMSH_CLI_DEFAULT_TIMEOUT: 60 # Increase timeout for CLI commands
          PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
        run: platform environment:activate --no-wait ${{ github.event.pull_request.head.ref }}

  deactivate_environment:
    runs-on: ubuntu-latest
    # For non-forked PRs
    # Deactivate when a PR is closed
    # Don't need to run on merges since the integration takes care of it
    if: >-
      github.event.action == 'closed' &&
      github.event.pull_request.merged == false &&
      github.event.pull_request.head.repo.id == 21975579
    steps:
      # Set up workflow environment to use the Platform.sh CLI
      - name: Set up Platform.sh CLI
        uses: ./.github/actions/set-up-cli

      - name: Close environment
        env:
          PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
        run: platform environment:deactivate --no-delete-branch ${{ github.event.pull_request.head.ref }}

  deactivate_forked_environment:
    runs-on: ubuntu-latest
    # For forked PRs labelled as build-fork
    # Delete branch when a PR is closed
    if: >-
      github.event.action == 'closed' &&
      github.event.pull_request.head.repo.id != 21975579 &&
      contains(github.event.pull_request.labels.*.name, 'build-fork')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete branch
        # If the pr- branch exists, delete it from GitHub
        run: |
          BRANCH=$(git ls-remote --heads origin pr-${{ github.event.number }})
          echo $BRANCH

          if [[ -n $BRANCH ]]; then
            git push origin --delete pr-${{ github.event.number }}
          fi

        # Set up workflow environment to use the Platform.sh CLI
      - name: Set up Platform.sh CLI
        uses: ./.github/actions/set-up-cli

      - name: Delete environment
        env:
          PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
        run: platform environment:delete --delete-branch --no-wait pr-${{ github.event.number }}
